# EXAMPLE — do NOT commit real credentials.
# In production, use external-secrets-operator, sealed-secrets, or your
# cloud KMS to materialize this Secret. Required keys: GITHUB_TOKEN.
# Optional keys: ANTHROPIC_API_KEY (or other provider key), WSHM_LICENSE_KEY.
apiVersion: v1
kind: Secret
metadata:
  name: wshm-secrets
  namespace: wshm
type: Opaque
stringData:
  GITHUB_TOKEN: "ghp_replace_me"
  ANTHROPIC_API_KEY: "sk-ant-replace_me"
  # WSHM_LICENSE_KEY: "wshm_pro_replace_me"
