{{- if .Values.job.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wshm.fullname" . }}-oneshot
  labels:
    {{- include "wshm.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit | default 1 }}
  activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds | default 1800 }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished | default 3600 }}
  template:
    metadata:
      labels:
        {{- include "wshm.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "wshm.serviceAccountName" . }}
      restartPolicy: {{ .Values.restartPolicy | default "OnFailure" }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: wshm
          image: {{ include "wshm.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- include "wshm.args" (dict "userArgs" .Values.job.args "Values" .Values) | nindent 12 }}
          workingDir: /data
          env:
            {{- include "wshm.containerEnv" . | nindent 12 }}
          volumeMounts:
            {{- include "wshm.volumeMounts" . | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- include "wshm.volumes" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
