{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wshm.fullname" . }}
  labels:
    {{- include "wshm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.githubToken }}
  GITHUB_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.licenseKey }}
  WSHM_LICENSE_KEY: {{ . | quote }}
  {{- end }}
{{- end }}
