apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wshm

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - pvc.yaml
  - cronjob.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/name: wshm
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: wshm

images:
  - name: innovtech/wshm
    newTag: 0.28.2
