//! `wshm context` — Export repo state as LLM-ready markdown.
//!
//! Dumps issues, triages, PRs, analyses, merge queue, conflicts,
//! and stats into a single markdown document optimized for pasting
//! into a conversation with an LLM.

use anyhow::Result;

use crate::db::Database;

pub fn run(db: &Database, slug: &str) -> Result<()> {
    let output = build_context(db, slug)?;
    println!("{output}");
    Ok(())
}

pub fn build_context(db: &Database, slug: &str) -> Result<String> {
    let mut out = String::with_capacity(8192);

    out.push_str(&format!("# {slug} — Repository Context\n\n"));
    out.push_str(&format!(
        "_Generated by wshm on {}_\n\n",
        chrono::Utc::now().format("%Y-%m-%d %H:%M UTC")
    ));

    // ── Stats overview ──
    let open_issues = db.get_open_issues()?;
    let open_pulls = db.get_open_pulls()?;
    let untriaged = db.get_untriaged_issues()?;

    out.push_str("## Overview\n\n");
    out.push_str(&format!(
        "- **Open issues:** {} ({} untriaged)\n",
        open_issues.len(),
        untriaged.len()
    ));
    out.push_str(&format!("- **Open PRs:** {}\n", open_pulls.len()));

    let conflict_count = open_pulls
        .iter()
        .filter(|pr| pr.mergeable == Some(false))
        .count();
    if conflict_count > 0 {
        out.push_str(&format!("- **PRs with conflicts:** {conflict_count}\n"));
    }
    out.push('\n');

    // ── Issues ──
    if !open_issues.is_empty() {
        out.push_str("## Open Issues\n\n");
        for issue in &open_issues {
            let labels = if issue.labels.is_empty() {
                String::new()
            } else {
                format!(" [{}]", issue.labels.join(", "))
            };

            out.push_str(&format!("### #{} — {}{}\n", issue.number, issue.title, labels));

            // Add triage info if available
            if let Ok(Some(triage)) = db.get_triage_result(issue.number) {
                out.push_str(&format!(
                    "**Triage:** {} | priority: {} | confidence: {:.0}%\n",
                    triage.category,
                    triage.priority.as_deref().unwrap_or("unset"),
                    triage.confidence * 100.0
                ));
                if let Some(ref summary) = triage.summary {
                    out.push_str(&format!("> {summary}\n"));
                }
            }

            // Add body (truncated)
            if let Some(ref body) = issue.body {
                let trimmed = body.trim();
                if !trimmed.is_empty() {
                    let truncated = if trimmed.len() > 500 {
                        let end = crate::ai::prompts::truncate_utf8(trimmed, 500);
                        format!("{}…", &trimmed[..end])
                    } else {
                        trimmed.to_string()
                    };
                    out.push_str(&format!("\n{truncated}\n"));
                }
            }
            out.push('\n');
        }
    }

    // ── Pull Requests ──
    if !open_pulls.is_empty() {
        out.push_str("## Open Pull Requests\n\n");
        for pr in &open_pulls {
            let labels = if pr.labels.is_empty() {
                String::new()
            } else {
                format!(" [{}]", pr.labels.join(", "))
            };

            let mergeable = match pr.mergeable {
                Some(true) => " ✓",
                Some(false) => " ✗conflicts",
                None => "",
            };

            out.push_str(&format!(
                "### PR #{} — {}{}{}\n",
                pr.number, pr.title, labels, mergeable
            ));

            // Add analysis if available
            if let Ok(Some(analysis)) = db.get_pr_analysis(pr.number) {
                out.push_str(&format!(
                    "**Analysis:** {} | risk: {} | type: {}\n",
                    analysis.summary, analysis.risk_level, analysis.pr_type
                ));
            }

            // Add body (truncated)
            if let Some(ref body) = pr.body {
                let trimmed = body.trim();
                if !trimmed.is_empty() {
                    let truncated = if trimmed.len() > 300 {
                        format!("{}…", &trimmed[..300])
                    } else {
                        trimmed.to_string()
                    };
                    out.push_str(&format!("\n{truncated}\n"));
                }
            }
            out.push('\n');
        }

        // ── Merge Queue ──
        out.push_str("## Merge Queue (ranked)\n\n");
        out.push_str("| # | PR | Score | Title |\n|---|-----|-------|-------|\n");

        let mut scored: Vec<_> = open_pulls
            .iter()
            .map(|pr| {
                let (score, _) = super::pr_health::score_pr(pr);
                (pr.number, pr.title.as_str(), score)
            })
            .collect();
        scored.sort_by(|a, b| b.2.cmp(&a.2));

        for (i, (num, title, score)) in scored.iter().enumerate() {
            let title_short = if title.len() > 60 {
                format!("{}…", &title[..59])
            } else {
                title.to_string()
            };
            out.push_str(&format!("| {} | #{num} | {score} | {title_short} |\n", i + 1));
        }
        out.push('\n');
    }

    // ── Recent triage decisions ──
    let triaged_issues: Vec<_> = open_issues
        .iter()
        .filter_map(|i| {
            db.get_triage_result(i.number)
                .ok()
                .flatten()
                .map(|t| (i.number, &i.title, t))
        })
        .collect();

    if !triaged_issues.is_empty() {
        out.push_str("## Triage Summary\n\n");
        out.push_str("| Issue | Category | Priority | Confidence | Simple Fix? |\n");
        out.push_str("|-------|----------|----------|------------|-------------|\n");
        for (num, title, t) in &triaged_issues {
            let title_short = if title.len() > 40 {
                format!("{}…", &title[..39])
            } else {
                title.to_string()
            };
            out.push_str(&format!(
                "| #{num} {title_short} | {} | {} | {:.0}% | {} |\n",
                t.category,
                t.priority.as_deref().unwrap_or("-"),
                t.confidence * 100.0,
                if t.is_simple_fix { "yes" } else { "no" }
            ));
        }
        out.push('\n');
    }

    out.push_str("---\n_Use this context to answer questions about the repository state, prioritize work, or plan next steps._\n");

    Ok(out)
}
